name: restaurant
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^3.0.0
  fluttertoast: ^8.0.8
  geolocator: ^5.1.5
  permission_handler: ^3.0.1
  google_maps_flutter: ^0.5.19
  flutter_staggered_grid_view: ^0.3.0
  http: ^0.13.4
  crypto: ^3.0.1
  flutter_typeahead: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: mont
      fonts:
        - asset: assets/Montserrat-Medium.ttf
